"""
Excel / XLSX tooling for cfo-helper close packs and supporting deliverables.

Pattern source: anthropics/skills/document-skills/xlsx (re-implemented, not copied
— Anthropic skills are source-available; we pattern-match their conventions
under our own license).

The four legacy functions (`new_close_pack`, `write_table`,
`write_value_with_provenance`, `render_exec_summary`) are preserved at the
package root so existing callers (`scripts.format`, `scripts.dispatch`,
`scripts.smoke`) keep working unchanged. New functionality lives in submodules:

- `scripts.xlsx.styles`   — color/number-format constants
- `scripts.xlsx.builders` — sheet templates (cover, P&L, KPI, deferred-rev, etc.)
- `scripts.xlsx.recalc`   — LibreOffice-based formula recalc (graceful fallback)
- `scripts.xlsx.qa`       — claim-id coverage + formula-error checks
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
from openpyxl import Workbook, load_workbook
from openpyxl.comments import Comment
from openpyxl.styles import Alignment, Font
from openpyxl.utils.dataframe import dataframe_to_rows

from scripts.xlsx.styles import HEADER_FILL, HEADER_FONT


def new_close_pack(path: Path, period: str) -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "Cover"
    ws["A1"] = f"Close Pack — {period}"
    ws["A1"].font = Font(size=18, bold=True)
    ws["A2"] = "Generated by cfo-helper. Hover any number for provenance (claim id)."
    wb.save(path)


def write_table(
    path: Path,
    sheet: str,
    df: pd.DataFrame,
    claim_ids_by_cell: dict[str, str] | None = None,
    *,
    claim_id_per_row: list[str] | None = None,
) -> None:
    """Write a DataFrame to a sheet, with optional claim_id provenance comments.

    Two comment modes (mutually exclusive; claim_ids_by_cell takes precedence
    for any cell it covers):

    - ``claim_id_per_row``: one claim id per data row (row 0 = first data row
      after the header). Every numeric cell in row R gets a ``claim_id: <id>``
      comment where ``id = claim_id_per_row[R]``.  Use this when all numeric
      columns in a row trace to the same source claim (the common case for
      line-item tables where one claim covers the row).

    - ``claim_ids_by_cell``: explicit {cell_ref: claim_id} mapping for
      fine-grained per-cell overrides (legacy behaviour, still supported).

    Callers on production paths MUST supply one of the two arguments or the
    assert_full_claim_coverage gate will reject the workbook.
    """
    wb = load_workbook(path)
    if sheet in wb.sheetnames:
        del wb[sheet]
    ws = wb.create_sheet(sheet)

    for r_idx, row in enumerate(dataframe_to_rows(df, index=False, header=True), start=1):
        for c_idx, val in enumerate(row, start=1):
            cell = ws.cell(row=r_idx, column=c_idx, value=val)
            if r_idx == 1:
                cell.fill = HEADER_FILL
                cell.font = HEADER_FONT
                cell.alignment = Alignment(horizontal="center")
            elif claim_id_per_row is not None:
                # r_idx == 2 corresponds to data row index 0
                data_row_idx = r_idx - 2
                if (
                    0 <= data_row_idx < len(claim_id_per_row)
                    and isinstance(val, (int, float))
                    and not isinstance(val, bool)
                ):
                    cell.comment = Comment(
                        f"claim_id: {claim_id_per_row[data_row_idx]}", "cfo-helper"
                    )

    if claim_ids_by_cell:
        for cell_ref, claim_id in claim_ids_by_cell.items():
            ws[cell_ref].comment = Comment(f"claim_id: {claim_id}", "cfo-helper")
    wb.save(path)


def write_value_with_provenance(path: Path, sheet: str, cell: str,
                                value, claim_id: str, *,
                                number_format: str | None = None) -> None:
    """Write a single value and attach a provenance comment with the upstream claim id."""
    wb = load_workbook(path)
    if sheet not in wb.sheetnames:
        wb.create_sheet(sheet)
    ws = wb[sheet]
    ws[cell] = value
    if number_format:
        ws[cell].number_format = number_format
    ws[cell].comment = Comment(f"claim_id: {claim_id}", "cfo-helper")
    wb.save(path)


def render_exec_summary(template_path: Path, context: dict) -> str:
    """Lightweight template render — Jinja2 if available, else str.format-ish."""
    try:
        from jinja2 import Template
        with template_path.open() as f:
            return Template(f.read()).render(**context)
    except ImportError:
        with template_path.open() as f:
            return f.read().format(**context)


__all__ = [
    "new_close_pack",
    "write_table",
    "write_value_with_provenance",
    "render_exec_summary",
]
